# Configure projects
name: 'lakehouse'
version: '0.0.1'
config-version: 2
require-dbt-version: [ ">=1.4.0", "<2.0.0" ]

# Configure profiles
profile: 'trino'

# Configure paths
model-paths: [ "dbt-model" ]
analysis-paths: [ "dbt-analysis" ]
test-paths: [ "dbt-test" ]
seed-paths: [ "dbt-seeds" ]
macro-paths: [ "dbt-macro" ]
snapshot-paths: [ "dbt-snapshot" ]
target-path: "target"
clean-targets:
  - "target"
  - "logs"
  - "dbt_modules"

# Configure variables
vars:
  debug_logs: "{{ env_var('DBT_EDR_DEBUG', True) }}"

# Configure models
models:
  lakehouse:
    +on_table_exists: drop
    staging:
      +schema: staging
      +materialized: view
    mart:
      +schema: mart
      +materialized: table

# Configure dispatches
dispatch:
  - macro_namespace: dbt_utils
    search_order: [ 'trino_utils', 'dbt_utils' ]
