# FROM apache/spark-py:v3.3.0
FROM apache/spark:3.3.3-scala2.12-java11-python3-ubuntu

USER root

WORKDIR ${SPARK_HOME}
ENV PATH="/opt/spark/sbin:/opt/spark/bin:${PATH}"

ENV SPARK_VERSION_SHORT=3.3
ENV SPARK_VERSION=3.3.3
ENV AWS_SDK_VERSION=1.12.48
ENV HADOOP_AWS_VERSION=3.3.4

# Configure SPARK
RUN apt-get update -y && apt-get install -y curl wget
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar \
    -o ${SPARK_HOME}/jars/hadoop-aws-${HADOOP_AWS_VERSION}.jar
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_SDK_VERSION}/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar \
    -o ${SPARK_HOME}/jars/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-hadoop-cloud_2.12/${SPARK_VERSION}/spark-hadoop-cloud_2.12-3.3.0.jar \
    -o ${SPARK_HOME}/jars/spark-hadoop-cloud_2.12-${SPARK_VERSION}.jar

# Configure HUDI
ENV HUDI_VERSION=0.13.1
ENV HUDI_CLI_HOME=/opt/hudi

RUN curl https://repo1.maven.org/maven2/org/apache/hudi/hudi-spark${SPARK_VERSION_SHORT}-bundle_2.12/${HUDI_VERSION}/hudi-spark${SPARK_VERSION_SHORT}-bundle_2.12-${HUDI_VERSION}.jar \
      -o ${SPARK_HOME}/jars/hudi-spark${SPARK_VERSION_SHORT}-bundle_2.12-${HUDI_VERSION}.jar

RUN mkdir -p /opt/hudi/conf || true;
RUN curl https://repo1.maven.org/maven2/org/apache/hudi/hudi-cli-bundle_2.12/${HUDI_VERSION}/hudi-cli-bundle_2.12-${HUDI_VERSION}.jar \
    -o ${HUDI_CLI_HOME}/hudi-cli-bundle_2.12-${HUDI_VERSION}.jar
RUN curl https://repo1.maven.org/maven2/org/apache/hudi/hudi-spark3.3-bundle_2.12/${HUDI_VERSION}/hudi-spark3.3-bundle_2.12-${HUDI_VERSION}.jar \
    -o ${HUDI_CLI_HOME}/hudi-spark3.3-bundle_2.12-${HUDI_VERSION}.jar
RUN curl https://raw.githubusercontent.com/apache/hudi/release-${HUDI_VERSION}/packaging/hudi-cli-bundle/hudi-cli-with-bundle.sh \
    -o ${HUDI_CLI_HOME}/hudi-cli-with-bundle.sh
RUN curl https://raw.githubusercontent.com/apache/hudi/release-${HUDI_VERSION}/packaging/hudi-cli-bundle/conf/hudi-env.sh \
    -o ${HUDI_CLI_HOME}/conf/hudi-env.sh
RUN curl https://raw.githubusercontent.com/apache/hudi/release-${HUDI_VERSION}/packaging/hudi-cli-bundle/conf/log4j2.properties \
    -o ${HUDI_CLI_HOME}/conf/log4j2.properties

ENV CLIENT_JAR=${SPARK_HOME}/jars/hadoop-aws-${HADOOP_AWS_VERSION}.jar:${SPARK_HOME}/jars/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar
ENV CLI_BUNDLE_JAR=${HUDI_CLI_HOME}/hudi-cli-bundle_2.12-${HUDI_VERSION}.jar
ENV SPARK_BUNDLE_JAR=${HUDI_CLI_HOME}/hudi-spark3.3-bundle_2.12-${HUDI_VERSION}.jar

# Configure ZSH
RUN apt-get install -y zsh git
RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true
ENV TERM xterm
ENV ZSH_THEME robbyrussell
RUN chsh -s /usr/bin/zsh

# Configure PYTHON
ENV PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.9.5-src.zip:$PYTHONPATH
COPY ./docker/jupyter/requirements.txt /opt/requirements.txt
RUN pip3 install -r /opt/requirements.txt
COPY ./docker/jupyter/jupyter_server_config.py /root/.jupyter/
COPY ./docker/jupyter/themes.jupyterlab-settings /root/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["tail", "-f", "/dev/null"]
