services:
  trino:
    container_name: trino
    hostname: trino
    image: "trinodb/trino:425"
    ports:
      - "8889:8889"
    volumes:
      - ./docker/trino/etc-coordinator:/etc/trino
    depends_on:
      - hive-metastore

  trino-worker:
    container_name: trino-worker
    hostname: trino-worker
    image: "trinodb/trino:425"
    volumes:
      - ./docker/trino/etc-worker:/etc/trino
    depends_on:
      - trino
