services:
  flink-jobmanager:
    build:
      dockerfile: ./docker/flink/Dockerfile-flink1.16
    image: 1ambda/lakehouse:flink-1.16
    container_name: flink-jobmanager
    hostname: flink-jobmanager
    entrypoint: |
      /bin/bash -c "
      export HADOOP_CLASSPATH=`/opt/hadoop/bin/hadoop classpath`; 
      /docker-entrypoint.sh jobmanager;
      "

    working_dir: /opt/flink
    ports:
      - "8081:8081"
      - "6123:6123"

    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - S3_ENDPOINT=http://minio:9000
      - S3_PATH_STYLE_ACCESS=true
      - |
        FLINK_PROPERTIES=
        fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
        fs.s3a.access.key: minio 
        fs.s3a.secret.key: minio123 
        fs.s3a.endpoint: http://minio:9000
        fs.s3a.path.style.access: true
        jobmanager.rpc.address: flink-jobmanager

    volumes:
      - ./docker/flink/hadoop-core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./docker/flink/hadoop-hive-site.xml:/opt/flink/conf/hive-site.xml
      - ./docker/flink/flink-sql-hudi.sh:/opt/flink-client/flink-sql-hudi
      - ./docker/flink/flink-init-hudi.sql:/opt/flink-client/flink-init-hudi.sql
      - ./docker/flink/flink-sql-iceberg.sh:/opt/flink-client/flink-sql-iceberg
      - ./docker/flink/flink-init-iceberg.sql:/opt/flink-client/flink-init-iceberg.sql

  flink-taskmanager:
    build:
      dockerfile: ./docker/flink/Dockerfile-flink1.16
    image: 1ambda/lakehouse:flink-1.17
    container_name: flink-taskmanager
    hostname: flink-taskmanager
    entrypoint: |
      /bin/bash -c "
      export HADOOP_CLASSPATH=`/opt/hadoop//bin/hadoop classpath`; 
      /docker-entrypoint.sh taskmanager;
      "
    working_dir: /opt/flink

    scale: 1
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - S3_ENDPOINT=http://minio:9000
      - S3_PATH_STYLE_ACCESS=true
      - |
        FLINK_PROPERTIES=
        fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
        fs.s3a.access.key: minio 
        fs.s3a.secret.key: minio123 
        fs.s3a.endpoint: http://minio:9000
        fs.s3a.path.style.access: true
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2

    volumes:
      - ./docker/flink/hadoop-core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./docker/flink/hadoop-hive-site.xml:/opt/flink/conf/hive-site.xml

    depends_on:
      - flink-jobmanager