FROM flink:1.17.1-scala_2.12-java11

ENV FLINK_VERSION_SHORT=1.17
ENV FLINK_VERSION=1.17.1
ENV AWS_SDK_VERSION=1.12.48
ENV HADOOP_AWS_VERSION=3.3.4

# Configure Hadoop
WORKDIR /opt
RUN curl -L http://archive.apache.org/dist/hadoop/common/hadoop-${HADOOP_AWS_VERSION}/hadoop-${HADOOP_AWS_VERSION}.tar.gz -o /opt/hadoop-${HADOOP_AWS_VERSION}.tar.gz
RUN tar xzvf hadoop-${HADOOP_AWS_VERSION}.tar.gz && rm hadoop-${HADOOP_AWS_VERSION}.tar.gz

RUN ln -s /opt/hadoop-${HADOOP_AWS_VERSION} /opt/hadoop
ENV HADOOP_HOME="/opt/hadoop"
ENV HIVE_VERSION=3.1.3

RUN mkdir -p /opt/flink/plugins/flink-s3-fs-hadoop
RUN curl -L https://repo1.maven.org/maven2/org/apache/flink/flink-s3-fs-hadoop/${FLINK_VERSION}/flink-s3-fs-hadoop-${FLINK_VERSION}.jar \
    -o ${FLINK_HOME}/plugins/flink-s3-fs-hadoop/flink-s3-fs-hadoop-${FLINK_VERSION}.jar
RUN curl -L https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-hive-${HIVE_VERSION}_2.12/1.17.1/flink-sql-connector-hive-${HIVE_VERSION}_2.12-${FLINK_VERSION}.jar \
    -o ${FLINK_HOME}/lib/flink-sql-connector-hive-${HIVE_VERSION}_2.12-${FLINK_VERSION}.jar

# Configure FLINK
RUN curl -L https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar \
    -o ${FLINK_HOME}/lib/hadoop-aws-${HADOOP_AWS_VERSION}.jar
RUN curl -L https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_SDK_VERSION}/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar \
    -o ${FLINK_HOME}/lib/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar

# Configure ICEBERG
ENV ICEBERG_VERSION=1.3.1
ENV AWS_SDK_BUNDLE_VERSION=2.20.18
RUN curl -L https://repo1.maven.org/maven2/software/amazon/awssdk/bundle/${AWS_SDK_BUNDLE_VERSION}/bundle-${AWS_SDK_BUNDLE_VERSION}.jar \
    -o ${FLINK_HOME}/lib/aws-bundle-${AWS_SDK_BUNDLE_VERSION}.jar
RUN curl -L https://repo1.maven.org/maven2/software/amazon/awssdk/url-connection-client/${AWS_SDK_BUNDLE_VERSION}/url-connection-client-${AWS_SDK_BUNDLE_VERSION}.jar \
    -o ${FLINK_HOME}/lib/url-connection-client-${AWS_SDK_BUNDLE_VERSION}.jar
RUN curl -L https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-flink-runtime-${FLINK_VERSION_SHORT}/${ICEBERG_VERSION}/iceberg-flink-runtime-${FLINK_VERSION_SHORT}-${ICEBERG_VERSION}.jar \
    -o ${FLINK_HOME}/lib/iceberg-flink-runtime-${FLINK_VERSION_SHORT}-${ICEBERG_VERSION}.jar

# Configure Plugins
ENV KAFKA_VERSION=3.5.0
RUN curl -L https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/${FLINK_VERSION}/flink-sql-connector-kafka-${FLINK_VERSION}.jar \
    -o ${FLINK_HOME}/lib/flink-sql-connector-kafka-${FLINK_VERSION}.jar
RUN curl -L https://repo1.maven.org/maven2/org/apache/flink/flink-avro-confluent-registry/${FLINK_VERSION}/flink-avro-confluent-registry-${FLINK_VERSION}.jar \
    -o ${FLINK_HOME}/lib/flink-avro-confluent-registry-${FLINK_VERSION}.jar
RUN curl -L https://repo1.maven.org/maven2/org/apache/flink/flink-connector-kafka/${FLINK_VERSION}/flink-connector-kafka-${FLINK_VERSION}.jar \
    -o ${FLINK_HOME}/lib/flink-connector-kafka-${FLINK_VERSION}.jar
RUN curl -L https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/${KAFKA_VERSION}/kafka-clients-${KAFKA_VERSION}.jar \
    -o ${FLINK_HOME}/lib/kafka-clients-${KAFKA_VERSION}.jar

# Configure FLINK CLI
ENV SQL_CLIENT_HOME /opt/flink-client
ENV PATH="/opt/flink-client:${PATH}"
