name: check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  checks:
    name: pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.6.0

      - name: python-action
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: poetry-action
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true

      - name: poetry-install
        run: poetry install

      - name: dbt-action
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt deps --project-dir dbts/ --profiles-dir dbts/"

      - name: precommit-action
        uses: pre-commit/action@v3.0.0
        env:
          SKIP: sqlfluff-fix,sqlfluff-lint
        with:
          extra_args: --color=always --show-diff-on-failure
