name: check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  checks:
    name: pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.6.0
      - name: poetry-action
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true
      - name: poetry-install
        run: poetry install
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v3.0.0
